name: Run cypress Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone another repository
        uses: actions/checkout@v2
        with:
          repository: amlcloud/screensite
          ref: main
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
  #     - run: flutter test
      - run: flutter build web

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --browser chrome
      
      - name: Check test results
        id: test-results
        run: echo "::set-output name=status::$(npx cypress run --browser chrome --ci | grep -oP 'All specs passed!|\d+ failing')"

      - name: Set pull request status
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          STATUS="${{ steps.test-results.outputs.status }}"
          ACCESS_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_NAME="${{ github.repository }}"

          API_URL="https://api.github.com/repos/$REPO_NAME/check-runs"
          API_HEADERS="Accept: application/vnd.github.antiope-preview+json"
          DATA="{\"name\": \"Cypress Tests\", \"head_sha\": \"${{ github.sha }}\", \"status\": \"$STATUS\", \"output\": {\"title\": \"Cypress Tests\", \"summary\": \"Cypress tests $STATUS\"}}"

          curl -s -X POST $API_URL/$API_ENDPOINT \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "$API_HEADERS" \
            -d "$DATA"

          exit 0
      