
name: Run Cypress Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone another repository
        uses: actions/checkout@v2
        with:
          repository: amlcloud/screensite
          ref: main

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      # - name: Set up Chrome
      #   uses: browser-actions/setup-chrome@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Print Current Working Directory
        run: |
          echo "Current Working Directory:"
          pwd
          ls -lrt
      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: |
          echo "Checking flutter version building the build web"
          flutter --version
          flutter build web 

      - name: Archive web build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web

      - name: Start HTTP server
        id: start_server
        run: |
          echo "Server is going to be started"
          nohup npx http-server build/web -p 8080 > http-server.log 2>&1 &
          sleep 10 # Wait for the server to start
      
      - name: Check if URL is accessible
        run: |
          echo "Checking if URL is accessble------>"
          echo "Testing with server at $SERVER_URL"
          url="http://localhost:8080" # Replace this with your server URL
          status=$(curl -o /dev/null -w "%{http_code}" $url)
          if [ "$status" -eq 200 ]; then
            echo "URL is accessible."
          else
            echo "URL is not accessible. HTTP status code: $status"
            exit 1
          fi
      
      - name: Print Current Working Directory
        run: |
          echo "Current Working Directory:"
          pwd
          ls -lrt
      - name: Print File Content
        run: |
          cat http-server.log
      - name: Set up environment
        run: |
          # Create a directory if it doesn't exist
          mkdir -p CypressAutomation

          # Change to the directory
          cd CypressAutomation
          ls -lrt

      - name: Print Current Working Directory
        run: |
          echo "Current Working Directory:"
          pwd
          ls -lrt
          cd CypressAutomation
      - name: Clone another repository
        # uses: actions/checkout@v2
        run: |
          # Run the git branch command to print the current branch
          git clone  https://github.com/amlcloud/screen-autotest.git
        # with:
        #   repository: amlcloud/screen-autotest
        #   ref: ${{ github.event.pull_request.base.ref }}
        
      - name: Print the all the files after clone the code
        run: |
          echo "Current Working Directory:"
          pwd
          ls -lrt
          echo "screen auto test Working Directory:"
          cd screen-autotest
          git branch
          ls -lrt
      # - name: Print the all the files previous directory
      #   run: |
      #     echo "Current Working Directory:"
      #     pwd
      #     ls -lrt ../
      - name: Check if URL is accessible
        run: |
          ls -lrt ../../
          echo "Checking if URL is accessble------>"
          echo "Testing with server at $SERVER_URL"
          url="http://localhost:8080" # Replace this with your server URL
          status=$(curl -o /dev/null -w "%{http_code}" $url)
          if [ "$status" -eq 200 ]; then
            echo "URL is accessible."
          else
            echo "URL is not accessible. HTTP status code: $status"
            exit 1
          fi
      # - name: Concatenate paths
      #   run: |
      #     # Concatenate paths using ${{ github.workspace }} (current working directory)
      #     concatenated_path="${{ github.workspace }}/cypress/reports"
      #     echo "Concatenated path: $concatenated_path"
      
      # - name: Set up Chrome
      #   uses: browser-actions/setup-chrome@v1

      # - name: Install Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14

      # - name: Install dependencies
      #   run: npm install

      - name: Run Cypress tests
        run: |
          # Run the git branch command to print the current branch
          git branch
          cd screen-autotest
          git branch
          ls -lrt
          npm install
          REPO_NAME="${{ github.repository }}"
          echo "REPO name: $REPO_NAME"
          # Extract the branch name from GITHUB_REF
          # BRANCH_NAME=${GITHUB_REF#refs/heads/}
          # echo "Branch Name: $BRANCH_NAME"
          PR_BRANCH=${{ github.head_ref }}
          git fetch
          git checkout "$PR_BRANCH"
          # git checkout $BRANCH_NAME
          git branch
          npx cypress run --browser chrome --env -e2e 
      
      - name: Set pull request status
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          STATUS="${{ steps.test-results.outputs.status }}"
          ACCESS_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_NAME="${{ github.repository }}"
          API_URL="https://api.github.com/repos/$REPO_NAME/check-runs"
          API_HEADERS="Accept: application/vnd.github.antiope-preview+json"
          DATA="{\"name\": \"Cypress Tests\", \"head_sha\": \"${{ github.sha }}\", \"status\": \"$STATUS\", \"output\": {\"title\": \"Cypress Tests\", \"summary\": \"Cypress tests $STATUS\"}}"
          curl -s -X POST $API_URL/$API_ENDPOINT \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "$API_HEADERS" \
            -d "$DATA"
          exit 0

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: "${{ github.workspace }}/cypress/reports"
      