name: Run cypress Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --browser chrome
      
      - name: Check test results
        id: test-results
        run: echo "::set-output name=status::$(npx cypress run --browser chrome --ci | grep -oP 'All specs passed!|\d+ failing')"

      - name: Set pull request status
        uses: peter-evans/create-pull-request-status@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ steps.test-results.outputs.status }}
          fail-comment: "Cypress tests failed. Please fix the issues before merging."
